# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('duracion', models.DurationField()),
                ('tiempo_registrado', models.DurationField()),
                ('estatus', models.CharField(choices=[('1', 'Pendiente'), ('2', 'Completada')], db_index=True, max_length=1, verbose_name='Estatus de tarea')),
            ],
        ),
    ]
