# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='estatus',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completada', 'Completada')], db_index=True, max_length=1, verbose_name='Estatus de tarea'),
        ),
    ]
