# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_auto_20180403_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='tiempo_registrado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
