# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_auto_20180403_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='duracion',
            field=models.DurationField(blank=True),
        ),
    ]
