# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_auto_20180403_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='duracion',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='tiempo_registrado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
