# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_auto_20180403_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
